/**
 * Seeded demo data — used when DEMO_MODE is on (no Supabase configured).
 * Mirrors the database row shapes so swapping to live data is a 1:1 change.
 */
import type {
  Activity,
  Approval,
  AreaData,
  Client,
  CommentWithAuthor,
  Invoice,
  Notification,
  Profile,
  Project,
  ProjectDocument,
  ProjectImage,
  ProjectProgress,
} from "@/types/database";

export const demoProfile: Profile = {
  id: "00000000-0000-0000-0000-000000000001",
  email: "admin@rustika.co.id",
  full_name: "Ananda Rustika",
  avatar_url: null,
  role: "super_admin",
  staff_category: null,
  phone: "+62 812-0000-0001",
  client_id: null,
  is_active: true,
  created_at: "2025-01-04T08:00:00Z",
  updated_at: "2025-06-01T08:00:00Z",
};

export const demoClients: Client[] = [
  {
    id: "c1",
    name: "PT Vale Indonesia",
    company: "PT Vale Indonesia Tbk",
    email: "project@vale.com",
    phone: "+62 21 524 9000",
    address: "Sorowako, Luwu Timur, Sulawesi Selatan",
    logo_url: null,
    share_token: "demo-token-vale",
    created_by: demoProfile.id,
    created_at: "2025-01-10T08:00:00Z",
    updated_at: "2025-01-10T08:00:00Z",
  },
  {
    id: "c2",
    name: "Pemkab Luwu Timur",
    company: "Pemerintah Kabupaten Luwu Timur",
    email: "setda@luwutimurkab.go.id",
    phone: "+62 474 321 100",
    address: "Malili, Luwu Timur, Sulawesi Selatan",
    logo_url: null,
    share_token: "demo-token-luwu",
    created_by: demoProfile.id,
    created_at: "2025-02-02T08:00:00Z",
    updated_at: "2025-02-02T08:00:00Z",
  },
  {
    id: "c3",
    name: "CV Mandiri Karya",
    company: "CV Mandiri Karya Sejahtera",
    email: "admin@mandirikarya.co.id",
    phone: "+62 411 555 200",
    address: "Makassar, Sulawesi Selatan",
    logo_url: null,
    share_token: "demo-token-mandiri",
    created_by: demoProfile.id,
    created_at: "2025-03-15T08:00:00Z",
    updated_at: "2025-03-15T08:00:00Z",
  },
];

export const demoManager: Profile = {
  id: "pm1",
  email: "pm@rustika.co.id",
  full_name: "Bayu Pratama",
  avatar_url: null,
  role: "project_manager",
  staff_category: null,
  phone: "+62 812-0000-0010",
  client_id: null,
  is_active: true,
  created_at: "2025-01-05T08:00:00Z",
  updated_at: "2025-01-05T08:00:00Z",
};

export const demoProjects: Project[] = [
  {
    id: "p1",
    code: "RC-2025-001",
    name: "Kantor VALE Sorowako",
    client_id: "c1",
    project_type: "Konsultan Arsitektur",
    location: "Sorowako, Luwu Timur",
    area_size: 4500,
    project_manager_id: "pm1",
    start_date: "2025-02-01",
    end_date: "2025-09-30",
    contract_value: 1850000000,
    status: "DESIGN",
    progress: 62,
    description:
      "Perencanaan gedung kantor 3 lantai termasuk kajian teknis, SIMBG, dan survey topografi.",
    created_by: demoProfile.id,
    created_at: "2025-02-01T08:00:00Z",
    updated_at: "2025-06-10T08:00:00Z",
  },
  {
    id: "p2",
    code: "RC-2025-002",
    name: "Pemetaan Drone Kawasan Industri Malili",
    client_id: "c2",
    project_type: "Drone Mapping",
    location: "Malili, Luwu Timur",
    area_size: 125000,
    project_manager_id: "pm1",
    start_date: "2025-03-10",
    end_date: "2025-07-15",
    contract_value: 640000000,
    status: "DESIGN",
    progress: 38,
    description:
      "Pemetaan udara orthomosaic & DTM untuk perencanaan kawasan industri seluas 12.5 Ha.",
    created_by: demoProfile.id,
    created_at: "2025-03-10T08:00:00Z",
    updated_at: "2025-06-08T08:00:00Z",
  },
  {
    id: "p3",
    code: "RC-2025-003",
    name: "Kajian Teknis Gudang Mandiri Karya",
    client_id: "c3",
    project_type: "Kajian Teknis",
    location: "Makassar",
    area_size: 2200,
    project_manager_id: "pm1",
    start_date: "2025-04-01",
    end_date: "2025-08-01",
    contract_value: 320000000,
    status: "PBG",
    progress: 75,
    description: "Kajian teknis & pengurusan SIMBG gudang logistik 2 lantai.",
    created_by: demoProfile.id,
    created_at: "2025-04-01T08:00:00Z",
    updated_at: "2025-06-12T08:00:00Z",
  },
  {
    id: "p4",
    code: "RC-2024-014",
    name: "Renovasi Mess Karyawan VALE",
    client_id: "c1",
    project_type: "Pengawasan",
    location: "Sorowako, Luwu Timur",
    area_size: 1800,
    project_manager_id: "pm1",
    start_date: "2024-10-01",
    end_date: "2025-03-01",
    contract_value: 540000000,
    status: "SLF",
    progress: 100,
    description: "Pengawasan renovasi mess karyawan 40 unit.",
    created_by: demoProfile.id,
    created_at: "2024-10-01T08:00:00Z",
    updated_at: "2025-03-01T08:00:00Z",
  },
];

export const demoDocuments: ProjectDocument[] = [
  {
    id: "d1",
    project_id: "p1",
    category: "kajian_teknis",
    subcategory: null,
    name: "Kajian Teknis Struktur - Rev 3.pdf",
    file_path: "p1/kajian/kajian-struktur-rev3.pdf",
    file_url: null,
    file_type: "pdf",
    file_size: 4_512_000,
    version: 3,
    description: "Revisi perhitungan struktur pondasi.",
    storage: "supabase",
    uploaded_by: "pm1",
    created_at: "2025-06-10T03:00:00Z",
  },
  {
    id: "d2",
    project_id: "p1",
    category: "simbg",
    subcategory: "Arsitektur",
    name: "Denah Lantai 1-3 - Rev 2.dwg",
    file_path: "p1/simbg/denah-rev2.dwg",
    file_url: null,
    file_type: "dwg",
    file_size: 8_900_000,
    version: 2,
    description: "Gambar arsitektur untuk pengajuan SIMBG.",
    storage: "supabase",
    uploaded_by: "pm1",
    created_at: "2025-06-09T03:00:00Z",
  },
  {
    id: "d3",
    project_id: "p1",
    category: "simbg",
    subcategory: "Struktur",
    name: "Gambar Struktur Pondasi.pdf",
    file_path: "p1/simbg/struktur-pondasi.pdf",
    file_url: null,
    file_type: "pdf",
    file_size: 6_200_000,
    version: 1,
    description: null,
    storage: "supabase",
    uploaded_by: "pm1",
    created_at: "2025-06-05T03:00:00Z",
  },
  {
    id: "d4",
    project_id: "p1",
    category: "survey",
    subcategory: null,
    name: "Berita Acara Survey Topografi.pdf",
    file_path: "p1/survey/ba-topografi.pdf",
    file_url: null,
    file_type: "pdf",
    file_size: 1_200_000,
    version: 1,
    description: "Berita acara hasil survey lapangan.",
    storage: "supabase",
    uploaded_by: "pm1",
    created_at: "2025-05-20T03:00:00Z",
  },
];

export const demoImages: ProjectImage[] = [
  {
    id: "img1",
    project_id: "p1",
    category: "existing",
    title: "Kondisi lahan eksisting - sisi utara",
    file_path: "p1/img/existing-1.jpg",
    file_url:
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80",
    file_size: 2_100_000,
    tags: ["lahan", "eksisting"],
    taken_at: "2025-02-12T02:00:00Z",
    storage: "supabase",
    uploaded_by: "pm1",
    created_at: "2025-02-12T05:00:00Z",
  },
  {
    id: "img2",
    project_id: "p1",
    category: "survey",
    title: "Pengukuran titik koordinat",
    file_path: "p1/img/survey-1.jpg",
    file_url:
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80",
    file_size: 1_800_000,
    tags: ["survey", "koordinat"],
    taken_at: "2025-02-15T02:00:00Z",
    storage: "supabase",
    uploaded_by: "pm1",
    created_at: "2025-02-15T05:00:00Z",
  },
  {
    id: "img3",
    project_id: "p1",
    category: "progress",
    title: "Progress pekerjaan minggu ke-12",
    file_path: "p1/img/progress-1.jpg",
    file_url:
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80",
    file_size: 2_400_000,
    tags: ["progress", "konstruksi"],
    taken_at: "2025-05-30T02:00:00Z",
    storage: "supabase",
    uploaded_by: "pm1",
    created_at: "2025-05-30T05:00:00Z",
  },
  {
    id: "img4",
    project_id: "p1",
    category: "final",
    title: "Render desain final fasad",
    file_path: "p1/img/final-1.jpg",
    file_url:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    file_size: 3_100_000,
    tags: ["render", "fasad", "final"],
    taken_at: "2025-06-01T02:00:00Z",
    storage: "supabase",
    uploaded_by: "pm1",
    created_at: "2025-06-01T05:00:00Z",
  },
];

export const demoProgress: ProjectProgress[] = [
  {
    id: "pr1",
    project_id: "p1",
    report_date: "2025-03-15",
    progress_percent: 20,
    division: "Survey",
    description: "Survey topografi & pengukuran lahan selesai.",
    obstacle: "Cuaca hujan menghambat pengukuran 2 hari.",
    solution: "Penjadwalan ulang & penambahan tim.",
    documentation_urls: null,
    created_by: "pm1",
    created_at: "2025-03-15T08:00:00Z",
  },
  {
    id: "pr2",
    project_id: "p1",
    report_date: "2025-04-20",
    progress_percent: 40,
    division: "Arsitektur",
    description: "Konsep desain & gambar pra-rencana disetujui klien.",
    obstacle: null,
    solution: null,
    documentation_urls: null,
    created_by: "pm1",
    created_at: "2025-04-20T08:00:00Z",
  },
  {
    id: "pr3",
    project_id: "p1",
    report_date: "2025-05-25",
    progress_percent: 55,
    division: "Struktur",
    description: "Perhitungan struktur tahap awal selesai.",
    obstacle: "Perlu data sondir tambahan.",
    solution: "Koordinasi dengan tim geoteknik.",
    documentation_urls: null,
    created_by: "pm1",
    created_at: "2025-05-25T08:00:00Z",
  },
  {
    id: "pr4",
    project_id: "p1",
    report_date: "2025-06-10",
    progress_percent: 62,
    division: "SIMBG",
    description: "Berkas SIMBG tahap 1 diajukan ke dinas.",
    obstacle: null,
    solution: null,
    documentation_urls: null,
    created_by: "pm1",
    created_at: "2025-06-10T08:00:00Z",
  },
];

export const demoAreaData: AreaData = {
  id: "ad1",
  project_id: "p1",
  luas_site: 4500,
  luas_bangunan: 1620,
  luas_lantai: 4200,
  kdb: 36,
  klb: 1.8,
  kdh: 24,
  gsb: 8,
  notes: "Sesuai ketentuan RTRW Kawasan Sorowako.",
  created_by: "pm1",
  created_at: "2025-04-01T08:00:00Z",
  updated_at: "2025-05-01T08:00:00Z",
};

export const demoInvoices: Invoice[] = [
  {
    id: "inv1",
    project_id: "p1",
    invoice_number: "INV/RC/2025/001",
    termin: "Termin 1 (DP 30%)",
    amount: 555000000,
    issue_date: "2025-02-05",
    due_date: "2025-02-20",
    status: "paid",
    invoice_file_url: null,
    receipt_file_url: null,
    tax_file_url: null,
    notes: null,
    created_by: demoProfile.id,
    created_at: "2025-02-05T08:00:00Z",
    updated_at: "2025-02-18T08:00:00Z",
  },
  {
    id: "inv2",
    project_id: "p1",
    invoice_number: "INV/RC/2025/014",
    termin: "Termin 2 (40%)",
    amount: 740000000,
    issue_date: "2025-05-01",
    due_date: "2025-05-16",
    status: "sent",
    invoice_file_url: null,
    receipt_file_url: null,
    tax_file_url: null,
    notes: "Menunggu pembayaran klien.",
    created_by: demoProfile.id,
    created_at: "2025-05-01T08:00:00Z",
    updated_at: "2025-05-01T08:00:00Z",
  },
];

export const demoApprovals: Approval[] = [
  {
    id: "ap1",
    project_id: "p1",
    document_id: "d2",
    title: "Persetujuan Gambar Arsitektur Rev 2",
    description: "Mohon review denah lantai 1-3 sebelum diajukan SIMBG.",
    status: "pending",
    requested_by: "pm1",
    responded_by: null,
    response_note: null,
    responded_at: null,
    created_at: "2025-06-09T08:00:00Z",
  },
  {
    id: "ap2",
    project_id: "p1",
    document_id: "d1",
    title: "Persetujuan Kajian Teknis Struktur Rev 3",
    description: "Final kajian struktur.",
    status: "approved",
    requested_by: "pm1",
    responded_by: "c1",
    response_note: "Disetujui, lanjutkan ke tahap berikutnya.",
    responded_at: "2025-06-11T08:00:00Z",
    created_at: "2025-06-10T08:00:00Z",
  },
];

export const demoComments: CommentWithAuthor[] = [
  {
    id: "cm1",
    project_id: "p1",
    parent_id: null,
    user_id: "c1",
    body: "Terima kasih, untuk fasad bisa ditambahkan aksen kayu di lobby?",
    attachment_url: null,
    mentions: ["pm1"],
    created_at: "2025-06-11T09:00:00Z",
    author: {
      ...demoManager,
      id: "c1",
      full_name: "Rini (PT Vale)",
      role: "client",
    },
    replies: [
      {
        id: "cm2",
        project_id: "p1",
        parent_id: "cm1",
        user_id: "pm1",
        body: "Siap Bu Rini, akan kami revisi di gambar fasad berikutnya.",
        attachment_url: null,
        mentions: ["c1"],
        created_at: "2025-06-11T10:15:00Z",
        author: demoManager,
      },
    ],
  },
];

export const demoActivities: Activity[] = [
  {
    id: "act1",
    project_id: "p1",
    user_id: "pm1",
    type: "upload",
    entity_type: "document",
    entity_id: "d1",
    description: "mengunggah Kajian Teknis Struktur - Rev 3.pdf",
    metadata: null,
    created_at: "2025-06-10T03:00:00Z",
  },
  {
    id: "act2",
    project_id: "p1",
    user_id: "c1",
    type: "approval",
    entity_type: "approval",
    entity_id: "ap2",
    description: "menyetujui Kajian Teknis Struktur Rev 3",
    metadata: null,
    created_at: "2025-06-11T08:00:00Z",
  },
  {
    id: "act3",
    project_id: "p1",
    user_id: "pm1",
    type: "progress",
    entity_type: "progress",
    entity_id: "pr4",
    description: "memperbarui progress menjadi 62%",
    metadata: null,
    created_at: "2025-06-10T08:00:00Z",
  },
  {
    id: "act4",
    project_id: "p1",
    user_id: "c1",
    type: "comment",
    entity_type: "comment",
    entity_id: "cm1",
    description: "menambahkan komentar pada diskusi proyek",
    metadata: null,
    created_at: "2025-06-11T09:00:00Z",
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "n1",
    user_id: demoProfile.id,
    project_id: "p1",
    type: "approval_required",
    title: "Approval diperlukan",
    body: "Gambar Arsitektur Rev 2 menunggu persetujuan.",
    link: "/projects/p1?tab=approval",
    is_read: false,
    created_at: "2025-06-09T08:00:00Z",
  },
  {
    id: "n2",
    user_id: demoProfile.id,
    project_id: "p1",
    type: "comment_added",
    title: "Komentar baru",
    body: "Rini (PT Vale) berkomentar pada Kantor VALE Sorowako.",
    link: "/projects/p1?tab=discussion",
    is_read: false,
    created_at: "2025-06-11T09:00:00Z",
  },
  {
    id: "n3",
    user_id: demoProfile.id,
    project_id: "p2",
    type: "document_uploaded",
    title: "Dokumen baru",
    body: "Orthomosaic kawasan Malili telah diunggah.",
    link: "/projects/p2?tab=drone",
    is_read: true,
    created_at: "2025-06-08T08:00:00Z",
  },
];

// ── Helpers used by demo pages ───────────────────────────────
export function getDemoClientName(clientId: string): string {
  return demoClients.find((c) => c.id === clientId)?.name ?? "Unknown";
}

export function getDemoProject(id: string): Project | undefined {
  return demoProjects.find((p) => p.id === id);
}

/** Monthly progress series for dashboard charts. */
export const demoMonthlyProgress = [
  { month: "Jan", progress: 8 },
  { month: "Feb", progress: 18 },
  { month: "Mar", progress: 31 },
  { month: "Apr", progress: 44 },
  { month: "Mei", progress: 56 },
  { month: "Jun", progress: 69 },
];

/** Progress per division for dashboard chart. */
export const demoDivisionProgress = [
  { division: "Survey", progress: 90 },
  { division: "Arsitektur", progress: 72 },
  { division: "Struktur", progress: 65 },
  { division: "MEP", progress: 48 },
  { division: "SIMBG", progress: 55 },
];
